customhost = "employee.cb2xuycq0ncu.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "nheelammitthera-employee"
customregion = "us-east-1"
